# Computational Linear Algebra: Assignment 2

### 3. Write the Python function to generate the Adjoint Matrix of 3 x 3 Matrix, without using NumPy libraries. (Use the function in Question No: 1 and 2, function for matrix transpose in question number 2 in assignment No. 1).Write python code find out the Adjoint Matrix of the given 3 X3 Matrix using this function.

#### Input:

Elements of the 3 X 3 Matrix

#### Output:

Adjoint Matrix corresponding to the given 3 x3 Matrix.
Verify your result using NumPy Library

***
#### Solution:

The adjoint of a 3 x 3 matrix can be obtained by following two simple steps. First, we need to find the cofactor matrix of the given matrix, and then the transpose of a matrix of this cofactor matrix to obtain the adjoint of a matrix. 

***

In [76]:
# declaring library dependency
# declaring functions
import copy 
import numpy as np
#Take input from user and make sure it is a non-zero positive integer and not punctuations or string

def inputNumber(message):
    while True:
        try:
            userInput = int(input(message))
            if userInput <= 0:
                print("Enter Positive Integer Value!")
                continue
        except ValueError:
            print("Not an integer! Try again.")
            continue
        else:
            return userInput 
            break 

#Take input from user and make sure it is a number and not punctuations or string etc for the input of matrix elements

def inputElement(msg,no_of_elements):     
    while True:
        try:
            userInput = input(msg).split()
            if len(userInput)!= no_of_elements:
                print("No of elements not matching!")
                continue
            else:
                for ele in userInput:
                    float(ele)
        except ValueError:
            print("Not a number! Try again.")
            continue     
        else:
            return list(map(float,userInput)) 
            break    
            

            
# Creating the null Matrix for defined dimension default is 3X3 matrix

def createEmptyMatrix(rows=3,cols=3):
    mat = []
    for i in range(rows):
        mat.append([])
        for j in range(cols):
            mat[i].append(j*0)
    
    return mat

# Calculate the determinant of 2X2 matrix

def det2(m):
    a = m[0][0]*m[1][1] - m[1][0]*m[0][1]
    return a

# Calculate minor of the matrix
def minorMatrix(matrix,d):
    
    a = createEmptyMatrix() # Create empty matrix to store the values of determinant of minors
    for col in range(d):
        m = []
        
        m = copy.deepcopy(matrix)

        [l.pop(col) for l in m ]

        for row in range(d):
            r = m.copy()

            r.pop(row)
            
            # adding the minor value to the respective element in empty matrix to store values 
            # det2 is a function declared already and hence has been called directily inside this function
            
            a[row][col] += det2(r) 
            
            # Underneath loop is meant for printing individual minors for reference if needed
            '''
            print('M' + str(row+1) + str(col+1) + '\n')
            for i in range(d-1):
                print(r[i])
            print()
            '''
  
    return a

# Finding cofactor matrix for 3X3 matrix
# This function is dependent on minorMatrix() and createEmptyMatrix()
def cofactor3(m):
    x = minorMatrix(m,3)
    for i in range(3):
        for j in range(3):
            x[i][j] = x[i][j]*(-1)**(i+j)
    return x

# Finding Transpose of a matrix 3 X 3
def transpose3(m):
    x = createEmptyMatrix()
    for i in range(3):
        for j in range(3):
            x[i][j] += m[j][i]
    return x

def adjMatrix3(m):
    x = cofactor3(m)
    x = transpose3(x)
    print("Adjoint Matrix : \n")
    for i in range(3):
        print(x[i])
    print()
    return x


In [77]:
#Get the elements for 3X3 matrix
print("Creating 3X3 Matrix \n")
m = 3
mx = []
# Take input of the elements in the matrix
for i in range(m):
        mxTemp = inputElement("Enter elements for Matrix Row " + str(i+1) + " containing " + str(m) + " elements ", m)
        mx.append(mxTemp)

Creating 3X3 Matrix 

Enter elments for Matrix Row 1 containing 3 elements 2 3 4
Enter elments for Matrix Row 2 containing 3 elements 4 65 6
Enter elments for Matrix Row 3 containing 3 elements 4 5 7


In [81]:
b = adjMatrix3(mx)
print()

# numpy has been imported as np already in the notebook
det = np.linalg.det(mx)
inv = np.linalg.inv(mx)
adj = inv*det
print('Adjoint of matrix using Numpy : \n')
print(adj)

Adjoint Matrix : 

[425.0, -1.0, -242.0]
[-4.0, -2.0, 4.0]
[-240.0, 2.0, 118.0]


Adjoint of matix using Numpy : 

[[ 425.   -1. -242.]
 [  -4.   -2.    4.]
 [-240.    2.  118.]]
